language: node_js
node_js:
- '11'
install:
- travis_retry npm ci
script:
- npm run lint
- npm run build
- npm run build-app
deploy:
- provider: npm
  email: stefandesu@exo.pm
  api_key:
    secure: Vr0fu3NveCX8pRlarYXdKYnVCjoBryCS6LQqRPJXxqDoVcHSgWXVvfB4RtFpgwomIAk2by3R5JPrDeaKwOLsf6X62XZhekbulaX7mVOFsrI18m+gJ8H7cLHyC9HM/QT759sffdTJd5Z0akGYL2MfnO692GyTI9ldZJ6dz7m6KqDA3JbiVBg9U9qAhkjcWLlbAZB0vofCU/ZbjckBN7Q0WLYSO1gejtqimK60OqLA6FGWK85g0KRivsaV4Vp4gz36SseOi1lxY8w3oORijz/rYUM7zOHolgmItXdaC8FrrpddFDk7+15Mz9ttYn48QgVYkBBRQPJCKkCwAShSCXUftauGmrVk/G1hR9abAXMAOhDOV/u1iopMrKN7d+51H+qQlOmTvnZuq+IOwd0i2UfdNxvtLX8W35XnbzZHzq81rBj2Ii2iSUMcPz6bb9e8JWa7HYNFr8DXRlqxtq0YfWhHHGZM5D1FbmBF6ow/Mz+EGa6jp5Zrk4EhQie7yZUZkgfTis466+E64kwZ/ExLDCdlocHON+sqoJpFMx4t70jy5+GayGzPUaXUckGDwwQRJXAYFZm8WJHXdpm9YaLH3O993HYoMix5dScONdRcAiB7iUwLBe6Nzx/H2Us78UFNXG3Y4xqwR6qIHA9Y/BQTw6Ps7SRYkDd+4vsUAmRLoDQY4B4=
  on:
    tags: true
    repo: stefandesu/cocoda-vue-tabs
- provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
