language: node_js
node_js:
- '11'
install:
- travis_retry npm ci
script:
- npm run lint
- npm run build
- npm run build-app
deploy:
- provider: npm
  email: stefandesu@exo.pm
  api_key:
    secure: RR56dZScp+/rogDXWkw6JNg5zwqkIMkCYh5YlUgd0LYRJ8WLnCRAuHNYCJRIz8gR26XCZk4s/x4wPU6+5r+NHW3lWmrQlXXpDpCajaivxFGb2LuoR6zkAS26PIES99rCVscgqbeYxmvGXVGleSrFZTuO4x00bFHRz6x7474rlcI0cb1a/ckDExuo+FgFNPb1M5rx0e3wySKzeaY1MytiGrTBtpAnIzlHkTE6U1GXKviB7/t8M/NvblHs+chRT/fky7HignPxfCzC0wMMctEYEwMz9ebcLmPX9abaD4a0KKbFe7cRxiGXfCbYu9jLwOzssrhZx5A85fjb88gtAQ4VF2+mEslRKZOG1H/w3TI1uyaCUcMm1A5UF6USgo5JES/Xh3W4iLIha27Q3DyE7FIF6FMiZsGFcJaTFcJVPHHBqPaoWNiihw46b+hdnNiNGoUwYdqCdRrMCyKtYP8zm/pPx1qqo5DNHLUB1DcQSBwyZTEDSq5vdY8hiQ9AZGsTfEJGKvxT0pxG0rb52TVIDvl7ldHWw8L8fkB6RoydEuzvK699BDRS8V9Y6eElKyPBK8Sp/Bp2EK+ZHE1z4yc8cuL0ABLmsz1bibsn7+/4EgWVQZPy9E2nEwx18UgL800R3/XVrPpMoUI2B+bAX61aORf9jdf40vSWwNf6sV/Qr8WTVaE=
  on:
    tags: true
    repo: stefandesu/cocoda-vue-tabs
- provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
